create table car_details (
      id bigint generated by default as identity,
       name varchar(255),
       price numeric(38,2),
       primary key (id)
);

create table car_owners (
   id bigint generated by default as identity,
    primary key (id)
);

create table car_owners_cars (
   car_owner_id bigint not null,
    cars_id bigint not null
);

create table car_owners_orders (
   car_owner_id bigint not null,
    orders_id bigint not null
);

create table cars (
   id bigint generated by default as identity,
    brand varchar(255),
    model varchar(255),
    number_plate varchar(255),
    production_year integer,
    owner_id bigint,
    primary key (id)
);

create table orders (
   id bigint generated by default as identity,
    acceptation_date timestamp(6),
    completion_date timestamp(6),
    description varchar(255),
    price numeric(38,2),
    status varchar(255),
    car_id bigint,
    primary key (id)
);

create table orders_details (
   order_id bigint not null,
    details_id bigint not null
);

create table orders_overhauls (
   order_id bigint not null,
    overhauls_id bigint not null
);

create table overhauls (
   id bigint generated by default as identity,
    is_paid boolean,
    price numeric(38,2),
    order_id bigint,
    repairer_id bigint,
    primary key (id)
);

create table repairers (
   id bigint generated by default as identity,
    full_name varchar(255),
    primary key (id)
);

create table repairers_completed_orders (
   repairer_id bigint not null,
    completed_orders_id bigint not null
);

alter table if exists car_owners_cars
   add constraint UK_95xdqdtnikjoruagv0dsiaxw2 unique (cars_id);

alter table if exists car_owners_orders
   add constraint UK_5r0lx2k325b9rden9ijyxdfq8 unique (orders_id);

alter table if exists repairers_completed_orders
   add constraint UK_4fx64lqmxuxb047v41keiktlm unique (completed_orders_id);

alter table if exists car_owners_cars
   add constraint FKlp4yqp054wns0jfi8m4k2kiog
   foreign key (cars_id)
   references cars;

alter table if exists car_owners_cars
   add constraint FKpaquvhq4q7xn7ha9qw9gb07y7
   foreign key (car_owner_id)
   references car_owners;

alter table if exists car_owners_orders
   add constraint FKf92qllhtgpfjvp856tche7ow6
   foreign key (orders_id)
   references orders;

alter table if exists car_owners_orders
   add constraint FK6y1bha5n50fw4xbb3ya4xmd75
   foreign key (car_owner_id)
   references car_owners;

alter table if exists cars
   add constraint FKoeqwfkm3sp26dhfekdbmysece
   foreign key (owner_id)
   references car_owners;

alter table if exists orders
   add constraint FKd2p23ixwrrt395glgi9nnbj23
   foreign key (car_id)
   references cars;

alter table if exists orders_details
   add constraint FKpu167wf7es99776qa9pm68otp
   foreign key (details_id)
   references car_details;

alter table if exists orders_details
   add constraint FK5o977kj2vptwo70fu7w7so9fe
   foreign key (order_id)
   references orders;

alter table if exists orders_overhauls
   add constraint FKmmdsvxkrrmevqkr6dg632xbuh
   foreign key (overhauls_id)
   references overhauls;

alter table if exists orders_overhauls
   add constraint FK31ep2pew0e6lp2bwdo0kkg9cu
   foreign key (order_id)
   references orders;

alter table if exists overhauls
   add constraint FK65mb70c631ltujsxh6ro46vlx
   foreign key (order_id)
   references orders;

alter table if exists overhauls
   add constraint FKii264j0h06fi5hnol27w3b3le
   foreign key (repairer_id)
   references repairers;

alter table if exists repairers_completed_orders
   add constraint FKo01ls3e8g7hlaxvuwk3irsamn
   foreign key (completed_orders_id)
   references orders;

alter table if exists repairers_completed_orders
   add constraint FK82jurx3tyrlqfv1p77eye80fp
   foreign key (repairer_id)
   references repairers;
